### ISSUE TITLE
Accuracy differs substantially from Apple's iOS device emitters

### ISSUE THREAD

**Issue by macteo** [Estimote/iOS-Fleet-Management-SDK#19]
Hi there,
with our first tests the accuracy obtained with `(ESTBeacon *)beacon.iBeacon.accuracy` is very different with the one obtained with a virtual iBeacon using CoreLocation as emitter on an iOS device.

Probably the devices needs to be calibrated and the power level should be set with `writeBeaconPower:(ESTBeaconPower)power...` however the calibration procedure suggested by Apple's AirLocate sample code provides a number, but the `ESTBeaconPower` has completely different values:

```
typedef enum : char
{
    ESTBeaconPowerLevel1 = -30,
    ESTBeaconPowerLevel2 = -20,
    ESTBeaconPowerLevel3 = -16,
    ESTBeaconPowerLevel4 = -12,
    ESTBeaconPowerLevel5 = -8,
    ESTBeaconPowerLevel6 = -4,
    ESTBeaconPowerLevel7 = 0,
    ESTBeaconPowerLevel8 = 4
} ESTBeaconPower;

```

Do you have a conversion matrix or function?
What should we set to obtain accuracy in meters?

Best regards,
Matteo

**Comment by hepcat72** [comment]
Hi,

I have a general question about adjusting measuredPower to achieve more accurate distance estimates. I am not using a physical beacon, but rather BeaconOSX (i.e. my computer is my beacon), so I'm not concerned with battery life.  I've tried various values for measured power, but I haven't been able to achieve a much better accuracy, perhaps because I don't understand what's going on under the hood.  Currently, I have measured power set at 10, which I thought would yield good accuracy according to what I've read, but I constantly get triggered events when I'm perhaps 20 yards away from my computer, separated by 3+ walls.  Should I increase or decrease the measured power setting to get better accuracy?  Ideally, it would only trigger when I'm 1-4 yards away.

Thanks,
Rob
