### ISSUE TITLE
warnings more than 200

### ISSUE THREAD

**Issue by BaranBerk** [Estimote/iOS-Fleet-Management-SDK#245]
I have added pod 'EstimoteSDK' but when I run it says that Documentation issue showing firs 200 warnings only ?? It shows warnings in commented lines

**Comment by paulofierro** [comment]
The documentation appears to be quite outdated with `@params` referencing variables that have been since renamed as well as `@returns` on `void` methods.

I've made pull request https://github.com/Estimote/iOS-SDK/pull/246 with the changes. Until then I am using my fork by specifying the repo in my Podfile:

`pod 'EstimoteSDK', :git => 'https://github.com/paulofierro/iOS-SDK.git'`

Our project treats warnings as errors so this was our only option 🙂
